/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as MainRegisterRouteImport } from './routes/_main.register'
import { Route as MainLoginRouteImport } from './routes/_main.login'
import { Route as MainCreateRouteImport } from './routes/_main.create'
import { Route as MainPostIdEditRouteImport } from './routes/_main.$postId.edit'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainRegisterRoute = MainRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MainRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRoute,
} as any)
const MainCreateRoute = MainCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MainRoute,
} as any)
const MainPostIdEditRoute = MainPostIdEditRouteImport.update({
  id: '/$postId/edit',
  path: '/$postId/edit',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/create': typeof MainCreateRoute
  '/login': typeof MainLoginRoute
  '/register': typeof MainRegisterRoute
  '/': typeof MainIndexRoute
  '/$postId/edit': typeof MainPostIdEditRoute
}
export interface FileRoutesByTo {
  '/create': typeof MainCreateRoute
  '/login': typeof MainLoginRoute
  '/register': typeof MainRegisterRoute
  '/': typeof MainIndexRoute
  '/$postId/edit': typeof MainPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_main/create': typeof MainCreateRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/register': typeof MainRegisterRoute
  '/_main/': typeof MainIndexRoute
  '/_main/$postId/edit': typeof MainPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/create' | '/login' | '/register' | '/' | '/$postId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/create' | '/login' | '/register' | '/' | '/$postId/edit'
  id:
    | '__root__'
    | '/_main'
    | '/_main/create'
    | '/_main/login'
    | '/_main/register'
    | '/_main/'
    | '/_main/$postId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/register': {
      id: '/_main/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof MainRegisterRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/create': {
      id: '/_main/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof MainCreateRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$postId/edit': {
      id: '/_main/$postId/edit'
      path: '/$postId/edit'
      fullPath: '/$postId/edit'
      preLoaderRoute: typeof MainPostIdEditRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainCreateRoute: typeof MainCreateRoute
  MainLoginRoute: typeof MainLoginRoute
  MainRegisterRoute: typeof MainRegisterRoute
  MainIndexRoute: typeof MainIndexRoute
  MainPostIdEditRoute: typeof MainPostIdEditRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainCreateRoute: MainCreateRoute,
  MainLoginRoute: MainLoginRoute,
  MainRegisterRoute: MainRegisterRoute,
  MainIndexRoute: MainIndexRoute,
  MainPostIdEditRoute: MainPostIdEditRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
